---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minio-sc
  namespace: storage-heketi
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://{{ heketi_endpoint }}"
  volumetype: {{volumetype}}
  volumeoptions: "stat-prefetch off, quick-read off, read-ahead off, io-cache off, remote-dio on, quorum-type auto, server-quorum-type server"
mountOptions:
  - entry-timeout=0
  - attribute-timeout=0
