---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gluster-heketi
  namespace: storage-heketi
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://{{ heketi_endpoint }}"
  volumetype: {{volumetype}}
  volumeoptions: {{gluster_volumeoptions}}
mountOptions:
  - entry-timeout=0
  - attribute-timeout=0
